# Ahmet Numan Aytemiz's Blog Pages
title: Cyber Security Notes
author:
  name: Ahmet Numan Aytemiz
  email: ahmetnumanaytemiz@gmail.com
description: "My Labs, Notes and Blogs about Cyber Security"

# Build settings
remote_theme: jekyll/minima
